# Part of Moo UI. See LICENSE file for full copyright and licensing details.

{
    'name': 'Moo UI',
    'version': '19.0.1.0.0',
    'category': 'Technical',
    'summary': 'Reusable QWeb and Bootstrap UI components for Odoo',
    'author': 'WPMoo',
    'website': 'https://www.wpmoo.org',
    'license': 'OPL-1',
    'depends': ['web'],
    'data': [
        'components/icon.xml',
        'components/typography.xml',
        'components/sidebar.xml',
        'components/card.xml',
        'components/badge.xml',
        'components/empty.xml',
        'components/button.xml',
        'components/avatar.xml',
        'components/dialog.xml',
        'components/drawer.xml',
        'components/separator.xml',
        'components/skeleton.xml',
        'components/alert.xml',
        'components/breadcrumb.xml',
        'components/dropdown_menu.xml',
        'components/command.xml',
        'components/tabs.xml',
        'components/pagination.xml',
        'components/label.xml',
        'components/field.xml',
        'components/input.xml',
        'components/input_group.xml',
        'components/textarea.xml',
        'components/select.xml',
        'components/checkbox.xml',
        'components/radio_group.xml',
        'components/switch.xml',
        'components/slider.xml',
        'components/tooltip.xml',
        'components/popover.xml',
        'components/accordion.xml',
        'components/collapsible.xml',
        'components/progress.xml',
        'components/spinner.xml',
        'components/kbd.xml',
        'components/aspect_ratio.xml',
        'components/attachment.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'moo_ui/static/src/scss/tokens.scss',
            'moo_ui/static/src/components/typography/typography.scss',
            'moo_ui/static/src/components/card/card.scss',
            'moo_ui/static/src/components/badge/badge.scss',
            'moo_ui/static/src/components/empty/empty.scss',
            'moo_ui/static/src/components/button/button.scss',
            'moo_ui/static/src/components/avatar/avatar.scss',
            'moo_ui/static/src/components/dialog/dialog.scss',
            'moo_ui/static/src/components/drawer/drawer.scss',
            'moo_ui/static/src/components/separator/separator.scss',
            'moo_ui/static/src/components/skeleton/skeleton.scss',
            'moo_ui/static/src/components/alert/alert.scss',
            'moo_ui/static/src/components/breadcrumb/breadcrumb.scss',
            'moo_ui/static/src/components/dropdown_menu/dropdown_menu.scss',
            'moo_ui/static/src/components/command/command.scss',
            'moo_ui/static/src/components/command/command.js',
            'moo_ui/static/src/components/tabs/tabs.scss',
            'moo_ui/static/src/components/pagination/pagination.scss',
            'moo_ui/static/src/components/label/label.scss',
            'moo_ui/static/src/components/field/field.scss',
            'moo_ui/static/src/components/input/input.scss',
            'moo_ui/static/src/components/input_group/input_group.scss',
            'moo_ui/static/src/components/textarea/textarea.scss',
            'moo_ui/static/src/components/select/select.scss',
            'moo_ui/static/src/components/checkbox/checkbox.scss',
            'moo_ui/static/src/components/radio_group/radio_group.scss',
            'moo_ui/static/src/components/switch/switch.scss',
            'moo_ui/static/src/components/slider/slider.scss',
            'moo_ui/static/src/components/tooltip/tooltip.scss',
            'moo_ui/static/src/components/tooltip/tooltip.js',
            'moo_ui/static/src/components/popover/popover.scss',
            'moo_ui/static/src/components/popover/popover.js',
            'moo_ui/static/src/components/accordion/accordion.scss',
            'moo_ui/static/src/components/collapsible/collapsible.scss',
            'moo_ui/static/src/components/progress/progress.scss',
            'moo_ui/static/src/components/spinner/spinner.scss',
            'moo_ui/static/src/components/kbd/kbd.scss',
            'moo_ui/static/src/components/aspect_ratio/aspect_ratio.scss',
            'moo_ui/static/src/components/attachment/attachment.scss',
            'moo_ui/static/src/components/sidebar/sidebar.js',
            'moo_ui/static/src/components/sidebar/sidebar.scss',
        ],
    },
    'application': False,
    'installable': True,
}
